### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by MonicaSvs** [robingenz/capacitor-mlkit-plugin-demo#24]
I've installed the plugin @capacitor-mlkit/barcode-scanning and i've some problems. 

I've included the code of demo (only barcode-scanning), i've followed the instructions (https://capawesome.io/plugins/mlkit/barcode-scanning/), but some functions return errors because they are not recognized by android 
E.g. "BarcodeScanner.scan()" is not implemented on android
te sam problem for isSupported(), or getMaxZoomRatio

Msg: ERROR Error: Uncaught (in promise): Error: "BarcodeScanner.getMinZoomRatio()" is not implemented on android
                 Error: "BarcodeScanner.getMinZoomRatio()" is not implemented on android
                     at http://localhost/vendor.js:2478:19
                     at _ZoneDelegate.invoke (http://localhost/polyfills.js:495:160)
                     at Object.onInvoke (http://localhost/vendor.js:77636:25)
                     at _ZoneDelegate.invoke (http://localhost/polyfills.js:495:48)
                     at Zone.run (http://localhost/polyfills.js:266:37)
                     at http://localhost/polyfills.js:1427:28
                     at _ZoneDelegate.invokeTask (http://localhost/polyfills.js:522:173)
                     at http://localhost/vendor.js:77323:49
                     at AsyncStackTaggingZoneSpec.onInvokeTask (http://localhost/vendor.js:77323:30)
                     at _ZoneDelegate.invokeTask (http://localhost/polyfills.js:522:56)

Attach:
- AndroidManifest
- Build.gradle (app)
- Capacitor.Build.Gradle

- Device: Samsung A15
- OS: Android 14

[AndroidManifest.txt](https://github.com/robingenz/capacitor-mlkit-plugin-demo/files/15431556/AndroidManifest.txt)
[capacitor-build-gradle.txt](https://github.com/robingenz/capacitor-mlkit-plugin-demo/files/15431627/capacitor-build-gradle.txt)
[build.txt](https://github.com/robingenz/capacitor-mlkit-plugin-demo/files/15431628/build.txt)

**Comment by robingenz** [comment]
You seem to have an issue with the plugin and not with this demo app. Please create the issue in https://github.com/capawesome-team/capacitor-mlkit. I'm closing this issue for now.
